import Header from "@/components/layout/Header";
import "../styles/main.scss";

import { Cairo } from "next/font/google";

export const metadata = {
  title: "BeldiCook | Moroccan Taste",
  description: "Generated by create next app",
};

const cairo = Cairo({
  subsets: ["latin"],
  weight: ["1000", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-cairo",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`overflow-x-hidden ${cairo.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
